Repository ojs258/TestGitFlow, pull requests merged in 2023-10, with the labels that each got.

#6 2023-10-19 컨트롤러개선 컨트롤러 파일 수정
  controller/controllerTest.txt
Labels: 오진석

#7 2023-10-19 config 파일 생성
  config/config.txt
Labels: 최성민

#8 domain 수정 개선 오후 3:31
  domain/domainTest.txt
Labels: 김지호

#9 개선1
  service/serviceTest.txt
Labels: 김현수
